... shell ...

Let me create a comprehensive frontend application with all routes, proper navigation, and complete functionality. I'll implement a sidebar navigation system using shadcn/ui and ensure all routes are properly connected.
